other:
  mean: &mean [0.485, 0.456, 0.406]
  std: &std [0.229, 0.224, 0.225]
  scale: &scale 1.0
  workers: &workers 2
  num_classes: &num_classes 2
  ignore_label: &ignore_label 255
  rotate_angle: &rotate_angle [-180, 180]   
  label_map: &label_map
    - bg
    - cat

  category_map: &category_map
    - [bg]
    - [cat]

  color_map: &color_map
    - [0,   0,   0]
    - [128, 0, 100]

  class_weight: &class_weight [0.05, 1.0]
  input_size: &input_size [400, 400]

common:
  log_level: INFO
  seed: 0
  deterministic: True
  implement_layer: [SMore_seg]
  plugin_layer: []

data:
  train_data:
    batch_size: 4
    workers: *workers
    dataset:
      type: MaskDataset
      data_name: train
      delimiter: '||' 
      data_path:
          - root: ''
            path: /newdata/jiachen/project/fugui/train_cat.txt
          - root: ''
            path: /newdata/jiachen/project/fugui/train_other_cat.txt
          - root: ''
            path: /newdata/jiachen/project/fugui/train_voc_cat.txt
    transform:
      - &cvtColor
        type: CvtColor
        mode: BGR2RGB
      - type: SMore_seg::RandomScale
        scale: [0.8, 1.25]
      - type: SMore_seg::RandomCrop
        output_size: *input_size
      - &resize
        type: Resize
        output_size: *input_size
      - type: RandomHorizontalFlip
        prob: 0.5
      - type: RandomVerticalFlip
        prob: 0.5
      - type: RandomRotation  
        prob: 0.5
        hook_cfg:
          ignore_label: *ignore_label
        angle: *rotate_angle
      - type: RandomApply
        p: 0.2
        transforms:
          - type: PhotoMetricDistortion
      - &normalize
        type: Normalize
        mean: *mean
        std: *std
        scale: *scale
      - &toTensor
        type: ToTensor

  eval_data:
    batch_size: 1
    workers: *workers
    dataset:
      - type: MaskDataset
        data_name: val
        # category_map: *category_map
        delimiter: '||'
        data_path:
          - root: ''
            path: /newdata/jiachen/project/fugui/test.txt    
    transform:
      - *cvtColor
      - *resize
      - *normalize
      - *toTensor

  test_data:
    batch_size: 1
    workers: *workers
    dataset:
      - type: MaskDataset
        data_name: test
        # category_map: *category_map
        delimiter: '||'
        data_path:
          - root: ''
            path: /newdata/jiachen/project/fugui/test.txt    
    transform:
      - *cvtColor
      - *resize
      - *normalize
      - *toTensor

model:
  type: EncoderDecoder
  backbone:
    type: HRNetW18SmallV2
    pretrained_weights: /newdata/jiachen/project/boer/d8x/demo/hrnet_w18_v2.pth
  head:
    type: FCNHead
    num_classes: *num_classes
    in_index: [0, 1, 2, 3]
    kernel_size: 1
    input_transform: resize_concat
    losses:
      - type: CE
        num_classes: *num_classes
        ignore_label: *ignore_label
        class_weights: *class_weight
        weight: 1.8
      - type: Dice
        num_classes: *num_classes
        ignore_label: *ignore_label
        weight: 3.0

train:
  type: SimpleTrainer
  max_iter: &max-iter 15000
  ckpt_freq: 5000
  print_freq: 100
  optimizer:
    type: Adam
    lr: 0.001
  lr_scheduler:
    type: WarmupCosineLR
    max_iter: *max-iter
    warmup_iter: 300   

eval:
  type: SimpleInference
  evaluators:
    - type: PixelBasedEvaluator
      num_classes: *num_classes
      label_map: *label_map
      ignore_label: *ignore_label
  visualizer:
    type: ConcatVisualizer
    painters:
      - type: MaskPainter
        num_classes: *num_classes
        label_map: *label_map

visualize:
  type: ConcatVisualizer
  painters:
    - type: MaskPainter
      num_classes: *num_classes
      label_map: *label_map

deploy:
  type: OnnxDeploy
  shapes: [1, 3, 400, 400]

analyze:
  type: TransformAnalyzer
  sample: 10
  num_classes: *num_classes
  label_map: *label_map
